# Generated by Django 4.1.4 on 2023-01-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_is_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register',
            field=models.BooleanField(default=False),
        ),
    ]
