# Generated by Django 4.1.4 on 2023-01-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_piece_num_hard_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='matching_string',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
