# Generated by Django 4.1.4 on 2023-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_piece_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(default='555555', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref',
            field=models.CharField(default='[0]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pieces',
            field=models.CharField(default="['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']", max_length=5000),
        ),
    ]
