# Generated by Django 4.1.4 on 2023-01-21 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_profile_reset_code_alter_profile_pref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_md',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reset_code',
        ),
        migrations.AlterField(
            model_name='piece',
            name='arrangers',
            field=models.ManyToManyField(blank=True, related_name='arranged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='piece',
            name='extras',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='piece',
            name='performer_string',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref',
            field=models.CharField(blank=True, default='[0]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_comments',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='matching_string',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
