# Generated by Django 4.1.4 on 2022-12-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='name',
            new_name='piece_text',
        ),
    ]
