# Generated by Django 4.1.4 on 2022-12-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_piece_piece_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='piece_text',
            new_name='name',
        ),
    ]
