# Generated by Django 4.1.4 on 2023-01-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_pref_profile_pref_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pref',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pref_comments',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
