# Generated by Django 4.1.4 on 2023-01-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_profile_pref_alter_profile_pref_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='performer_string',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
