# Generated by Django 4.1.4 on 2023-01-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_piece_performer_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='num_hard_parts',
            field=models.IntegerField(default=1),
        ),
    ]
