# Generated by Django 4.1.4 on 2023-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_schedule_matching_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
