# Generated by Django 4.1.4 on 2023-01-22 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_profile_register_profile_create_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='availability_reset',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 0), verbose_name='last reset availability'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pref_reset',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 1, 0), verbose_name='last reset preferences'),
        ),
    ]
