# Generated by Django 4.1.4 on 2023-01-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_profile_create_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cursed_with_comic_sans',
            field=models.BooleanField(default=False),
        ),
    ]
